//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccCostSharingSequence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccCostSharingSequence()
        {
            this.AccSharingPercent = new HashSet<AccSharingPercent>();
        }
    
        public string chYM { get; set; }
        public string chHospital { get; set; }
        public int intSharingOrder { get; set; }
        public string chCostToShare { get; set; }
        public string nvCostName { get; set; }
        public string chAccNo { get; set; }
        public string nvAccName { get; set; }
        public string chSharingMethodType { get; set; }
        public string nvSharingMethodName { get; set; }
        public string nvDataSource { get; set; }
        public string nvFomula { get; set; }
        public string nvFitDepartment { get; set; }
        public string nvComment { get; set; }
        public string chDCFlag { get; set; }
        public string nvOriStatus { get; set; }
        public string nvAdjStatus { get; set; }
        public Nullable<System.DateTime> sdInputTime { get; set; }
        public string vcInputID { get; set; }
        public string vcComeFrom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccSharingPercent> AccSharingPercent { get; set; }
    }
}
