//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccSharingPercent
    {
        public string chYM { get; set; }
        public string chHospital { get; set; }
        public string nvSharingMethod { get; set; }
        public string chCostID { get; set; }
        public string nvCostName { get; set; }
        public string chShareToSecNo { get; set; }
        public string nvShareToSecName { get; set; }
        public string chShareToCostID { get; set; }
        public string nvShareToCostName { get; set; }
        public decimal deValue { get; set; }
        public Nullable<decimal> deValueOld { get; set; }
        public decimal dePercent { get; set; }
        public Nullable<decimal> dePercentOld { get; set; }
        public Nullable<System.DateTime> sdInputTime { get; set; }
        public string chInputID { get; set; }
        public string chComeFrom { get; set; }
    
        public virtual AccCostSharingSequence AccCostSharingSequence { get; set; }
    }
}
